version: 0.5.0
tool:    "omt-soundbank"
command: "build"
## output:  "background-atlas-0"
## output:  "${input:basename .png}"
output:  "base.omsb"
combine-inputs: false
input:
  - "base.soundbank"
parameters: {
}
cmd_line: "${tool} ${command} --use-version 3 --output ${output} --input ${input}"


# omt-soundbank build \
#   --use-version 3 \
#   --output ../fiiish-data/default.omsb  \
#   --input ../fiiish-content/sound/default.soundbank

--- 
# :TODO: move to entities, and combine as needed
tool:    "$asset"
command: "copy"
output:  "${input}"
input:
  - "*.wav"
