[package]
name = "rar-rs"
version = "0.1.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="rar"
path="src/rar_main.rs"

[dependencies]
anyhow = "1.0.58"
rand = "0.8.5"
serde = { version = "1.0.139", features = ["std","derive"] }
serde_yaml = "0.8.25"

[dependencies.oml-game]
path = "../../oml-game"
