r:
	cargo run --release

d:
	cargo run

cr:
	cargo check --release

c:
	cargo check
	
fmt:
	cargo +nightly fmt

cook:
	cd .. && ./cook.sh; cd -

pack:
	cd .. && ./workflow/helpers/pack_data.sh data/base base.omar paklist.txt music_mp3 && cp base.omar rar-rs/; cd -

test-noisy:
	cargo test -- --nocapture
