tool:    "omt-shader"
command: "build"
output:  "${input:basename}"
input:
  - "*.glsl"
parameters: {
}
cmd_line: "${tool} ${command} --mode transpile --output ${data_directory}/${output} --input ${input}"
