version: 0.5.0
tool:    "omt-font"
command: "create"
## output:  "background-atlas-0"
output:  "${input:basename .ttf}"
combine-inputs: false
input:
  - "*.ttf"
parameters: {
}
cmd_line: "${tool} ${command} --texsize 512 --size 32 --output ${data_directory}/${output} --distancefield-max-distance 4 --distancefield-scale 4 --input ${input}"


#omt-font create --border 2                  \
#  --texsize 1024 --size 104                 \
#  --output ../fiiish-data/pink_huge           \
#  --distancefield-max-distance 4 --distancefield-scale 4  \
#  --input ../fiiish-content/fonts/all_things_pink.ttf
