name: Release version

env:
  PROJECT: rar-rs

on:
  push:
    tags:
      - "*-test"  
  workflow_dispatch:
    inputs:
      project:
        description: 'Prefix for the project'
        required: true
        default: 'rar-rs'
        type: string
      # maybe we don't need this
      version:
        description: 'Version'
        required: true
        default: 'auto'
        type: choice
        options:
          - latest
          - auto
          - ref
      ref:
        description: 'The branch, tag, or SHA of the commit to build'
        required: false
        default: ''
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      PROJECT: ${{ steps.prepare.outputs.PROJECT }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Prepare
        id: prepare
        run: |
          echo "Prepare"
          echo "${{ toJSON(inputs) }}"
          # :HACK: to work around inconsistent github input behavior
          PROJECT="${{ env.PROJECT }}"
          if [[ ! -z "${{ inputs.project }}" ]]
          then
            PROJECT="${{ inputs.project }}"
          fi
          echo "${PROJECT}"
          echo "PROJECT=${PROJECT}" >> $GITHUB_ENV
          echo "PROJECT=${PROJECT}" >> $GITHUB_OUTPUT
      - name: Dump
        run: |
          echo "PROJECT (output): ${{steps.prepare.outputs.PROJECT}}"
          echo "PROJECT (env): ${{env.PROJECT}}"

  dump:
    name: Dump
    needs:
      - release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Dump
        env:
          THE_PROJECT: ${{ needs.release.outputs.PROJECT }}
        run: |
          echo "THE_PROJECT ${{ env.THE_PROJECT }}"
          exit -1

  pack_data:
    needs:
      - release
      - dump
    uses:  AndreasOM/rar-rs/.github/workflows/pack_rar_data.yaml@episode-0021
    with:
      project: ${{ needs.release.outputs.PROJECT }}
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref || github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build_package_and_sign_macos:
    needs:
      - release
      - pack_data
    uses:  AndreasOM/rar-rs/.github/workflows/build_package_and_sign_macos.yaml@episode-0021
    with:
      use_latest_data: false
      project: ${{ needs.release.outputs.PROJECT }}
      version: ${{ inputs.version }}
      ref: ${{ inputs.ref || github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CODESIGN_CERT: ${{ secrets.CODESIGN_CERT }}
      CODESIGN_CERT_PASS: ${{ secrets.CODESIGN_CERT_PASS }}
      CODESIGN_CERT_IDENTITY: ${{ secrets.CODESIGN_CERT_IDENTITY }}

  push_to_itchio:
    needs:
      - release
      - build_package_and_sign_macos
    uses:  AndreasOM/rar-rs/.github/workflows/push_to_itchio.yaml@episode-0021
    with:
      use_latest_app: false
      project: ${{ needs.release.outputs.PROJECT }}
      version: ${{ inputs.version }}
      ref: ${{ inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ITCHIO_API_KEY: ${{ secrets.ITCHIO_API_KEY }}


