name: Release version

env:
  PROJECT: rar-rs
on:
  push:
    tags:
      - "*-test"  
  workflow_dispatch:
    inputs:
      project:
        description: 'Prefix for the project'
        required: true
        default: 'rar-rs'
        type: string
      # maybe we don't need this
      version:
        description: 'Version'
        required: true
        default: 'auto'
        type: choice
        options:
          - latest
          - auto
          - ref
      ref:
        description: 'The branch, tag, or SHA of the commit to build'
        required: false
        default: ''
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Prepare & Info
        run: |
          echo "Prepare"
          echo "${{ toJSON(inputs) }}"
          # :HACK: to work around inconsistent github input behavior
          PROJECT="rar-rs"
          if [[ ! -z "${{ inputs.project }}" ]]
          then
            PROJECT="${{ inputs.project }}"
          fi
          echo "PROJECT=${PROJECT}" >> $GITHUB_ENV

  pack_data:
    uses:  AndreasOM/rar-rs/.github/workflows/pack_rar_data.yaml@episode-0021
    with:
      project: ${{env.PROJECT}}
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref || github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build_package_and_sign_macos:
    needs:
      - pack_data
    uses:  AndreasOM/rar-rs/.github/workflows/build_package_and_sign_macos.yaml@episode-0021
    with:
      use_latest_data: false
      project: ${{env.PROJECT}}
      version: ${{ inputs.version }}
      ref: ${{ inputs.ref || github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CODESIGN_CERT: ${{ secrets.CODESIGN_CERT }}
      CODESIGN_CERT_PASS: ${{ secrets.CODESIGN_CERT_PASS }}
      CODESIGN_CERT_IDENTITY: ${{ secrets.CODESIGN_CERT_IDENTITY }}

  push_to_itchio:
    needs: build_package_and_sign_macos
    uses:  AndreasOM/rar-rs/.github/workflows/push_to_itchio.yaml@episode-0021
    with:
      use_latest_app: false
      project: ${{env.PROJECT}}
      version: ${{ inputs.version }}
      ref: ${{ inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ITCHIO_API_KEY: ${{ secrets.ITCHIO_API_KEY }}


