--- # Player entity
    name: "player"
    type: "player"
    states:
     wait_for_start:
        first_frame: 0
        last_frame: 8
        size: [ 128.0, 128.0 ]
        offset: [ 0.0, 0.0 ]
        directions:
          left:
            template: "player-idle-left-"
          right:
            template: "player-idle-right-"
     idle:
        first_frame: 0
        last_frame: 8
        size: [ 128.0, 128.0 ]
        offset: [ 0.0, 0.0 ]
        directions:
          left:
            template: "player-idle-left-"
          right:
            template: "player-idle-right-"
     backflip:
        first_frame: 0
        last_frame: 48
        size: [ 128.0, 128.0 ]
        offset: [ 0.0, 0.0 ]
        directions:
          left:
            template: "player-backflip-left-"
          right:
            template: "player-backflip-right-"
